language: emacs-lisp
env:
  - EMACS=emacs24
  # - EMACS=emacs-snapshot
before_install:
  # Bootstrap Ansible
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install ansible
  - ansible-playbook -v playbook.yml
install:
  # Install our packages
  - make EMACS=$EMACS deps
script:
  # Run unit tests.
  - make EMACS=$EMACS test
